language: elixir
elixir:
  - 1.7.1
  - 1.8.1
otp_release:
  - 20.0
  - 21.0

env:
  - DATABASE_URL=postgres://postgres@127.0.0.1:5432/test

services:
  - postgresql

addons:
  postgresql: "9.5"

cache:
  directories:
    - _build
    - deps

before_script:
  - MIX_ENV=test mix compile --warnings-as-errors
  - MIX_ENV=test mix do ecto.create, ecto.migrate

script:
  - mix test
